In [7]:
import numpy as np

In [9]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i]= 1.0/ values[i]
    return output    
    

In [12]:
"""
Loop vs ufuncs
"""

big_array = np.random.randint(1,100,size=1000000)

%timeit compute_reciprocals(big_array)

4.71 s ± 536 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
%timeit 1/big_array

8.76 ms ± 601 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
np.random.seed(1)
arr_1=np.random.randint(10,size=(5))
arr_2=np.random.randint(10,size=(5))
print(arr_1,arr_2)

arr_1 = arr_1 - 2
print(arr_1)

arr_3= arr_1 + arr_2
print(arr_3)

arr_4 = np.random.randint(10,size=(3,5))
print(arr_4)

arr_5 = arr_4 ** 2
print(arr_5)


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]


In [21]:
x=np.arange(4)
print(x)
print(x+2)
print(x-3)
print(x*2)
print(x/3)
print(x*2)

[0 1 2 3]
[2 3 4 5]
[-3 -2 -1  0]
[0 2 4 6]
[0.         0.33333333 0.66666667 1.        ]
[0 2 4 6]


In [27]:
x = np.array([-2, -1, 0, 1, 2])
print (np.abs(x))
            
x = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(np.abs(x))
        

[2 1 0 1 2]
[5. 5. 2. 1.]


In [32]:
theta = np.linspace(0, np.pi, 3)
print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [48]:
x = np.arange(1,6)
print(x)

ag=np.add.reduce(x)
print(ag)

ag = np.multiply.reduce(x)
print(ag)

[1 2 3 4 5]
15
120


In [50]:
#accumulate

x = np.arange(1,6)
print(x)

ag=np.add.accumulate(x)
print(ag)

ag = np.multiply.accumulate(x)
print(ag)

[1 2 3 4 5]
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [54]:
np.random.seed(3)

arr = np.random.rand(100)
print(np.sum(arr))
%timeit sum(arr)

47.934404882589284
17.3 µs ± 1.53 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [56]:
%timeit np.sum(arr)

10 µs ± 662 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [58]:
print(np.any(arr>1)) 
print(np.all(arr<0))
print(np.max(arr))

False
False
0.9759954224729338


In [63]:
np.random.seed(5)
arr = np.random.randint(10,size=(3,4))
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
