In [3]:
import numpy as np

In [7]:
"""
Numpy arrange attributes
"""

print(np.arange(3))
print(np.arange(3,9))
print(np.arange(3,9,2))

[0 1 2]
[3 4 5 6 7 8]
[3 5 7]


In [22]:
np.random.seed(0)
arr1=np.random.randint(10,size= (2,3,4))
print(arr1)

[[[5 0 3 3]
  [7 9 3 5]
  [2 4 7 6]]

 [[8 8 1 6]
  [7 7 8 1]
  [5 9 8 9]]]


In [18]:

np.random.seed(0)
arr = np.random.randint(10,size= (3,4))
print(arr)
print('arr ndim',arr.ndim)
print('arr shape',arr.shape)
print('arr size',arr.size)
print('arr dtype',arr.dtype)
print('arr itemsize',arr.itemsize)
print('arr nbytes',arr.nbytes)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
arr ndim 2
arr shape (3, 4)
arr size 12
arr dtype int32
arr itemsize 4
arr nbytes 48


In [32]:
"""
slicing
"""

arr = np.arange(10)
print(arr)

print(arr[3:7])
print(arr[:5])
print(arr[5:])
print(arr[::3])
print(arr[2:8:2])

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [43]:
np.random.seed(2)
arr=np.random.randint(10 , size=(6,8))
print(arr)
arr_sub=arr[:2,:2]
print(arr_sub)
arr_sub[0,0]=99
print(arr_sub)
print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]
[[99  8  6  2  8  7  2  1]
 [ 5  4  4  5  7  3  6  4]
 [ 3  7  6  1  3  5  8  4]
 [ 6  3  9  2  0  4  2  4]
 [ 1  7  8  2  9  8  7  1]
 [ 6  8  5  9  9  9  3  0]]


In [48]:
"""
copy
"""

np.random.seed(2)
arr=np.random.randint(10 , size=(6,8))
print(arr)
arr_sub=arr[:2,:2].copy()
print(arr_sub)

arr_sub[0,0]=99
print(arr_sub)
print(arr)

[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]
[[8 8]
 [5 4]]
[[99  8]
 [ 5  4]]
[[8 8 6 2 8 7 2 1]
 [5 4 4 5 7 3 6 4]
 [3 7 6 1 3 5 8 4]
 [6 3 9 2 0 4 2 4]
 [1 7 8 2 9 8 7 1]
 [6 8 5 9 9 9 3 0]]


In [4]:
arr=np.arange(1,10) 
print(arr)

grid=arr.reshape(3,3) #사이즈가 다르면 출력에러가 난다.
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
"""
newaxis
"""
arr = np.array([1,2,3,])
print(arr)
print(arr.shape)
print()

arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape)
print()
arr_new = arr[:, np.newaxis]
print(arr_new)
print(arr_new.shape)

[1 2 3]
(3,)

[[1 2 3]]
(1, 3)

[[1]
 [2]
 [3]]
(3, 1)


In [19]:
"""
concatenate
"""
arr_1 = np.array([[1,2,3],[1,2,3]])
arr_2 = np.array([[4,5,6],[4,5,6]])
arr_3 = np.array([[7,8,9],[7,8,9]])

arr_total=np.concatenate([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [22]:
"""
split
"""

arr=[1,2,3,99,99,3,2,1]
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3, 5])
print(arr_1)
print(arr_2)
print(arr_3)


[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3]
[99 99]
[3 2 1]
