In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [9]:
#creating a numpy array

lst = [1, 2, 3, 4]

arr = np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>
int32


In [14]:
#dtype attribute
lst = [1.2, 1.3, 1.4]
arr = np.array(lst)
print(arr.dtype)

lst = [1, 2, 3]
arr = np.array(lst)
print(arr.dtype)

lst = ['1.2, 1.3, 1.4']
arr = np.array(lst)
print(arr.dtype)

lst = [1, 1.2, '1.2, 1.3, 1.4'] #u는 데이터타입이 짬뽕이라는걸 뜻함 
arr = np.array(lst)
print(arr.dtype)

float64
int32
<U13
<U32


In [24]:
"""
size comparsion of ndarray and list objects
"""
# getsizeof 를 통해 메모리 차지하는 공간비교
#처음에 비어있을때는 arr이 더 크지만 넣으면 넣을수록 메모리 차지하는 공간이 lst이 차지하는 공간이 더 커진다.
from sys import getsizeof

lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] #56 -> 64
print(getsizeof(lst))

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) # 104 -> 108
print(getsizeof(arr))

176
164


In [30]:
"""
operations with numpy arrays
"""

prices = [30,25,33,20,15,78]
prices_arr = np.array(prices)
#with a list
new_prices = [price-5 for price in prices]
print(new_prices)

#with a nbarray
prices_arr -= 5
print(prices_arr)

[25, 20, 28, 15, 10, 73]
[25 20 28 15 10 73]


In [46]:
"""
operations with Test Scores
"""

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

test_3_fixed = test_3 + 2
print(test_3_fixed)

total_grade = test_1 + test_2 + test_3_fixed
print(total_grade)

final_grade = total_grade / 3
print(final_grade)

student_scores = np.array([test_1, test_2, test_3_fixed])   #2차원 배열로 묶기
print(student_scores) 

jeremey_test_2 = student_scores[1, 3]
print(jeremey_test_2)

manual_adwoa_test_1 = np.array([student_scores[0, 1] ,student_scores[0, 2]])
print(manual_adwoa_test_1)

print(student_scores[:,4])
print(student_scores[:,-1])          

[89 87 74 92 94]
[260 281 248 276 272]
[86.66666667 93.66666667 82.66666667 92.         90.66666667]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
93
[94 88]
[87 91 94]
[87 91 94]


In [54]:
"""
logical operations with arrays
"""
# masking
a = np.array([10,2,2,4,5,8,7])
mask = a>5
print(mask)

# selecting using logical operations '&' , '|'
selected = a[a>5]
print(selected)

#combined logical operations

selected = a[(a>5) | (a<4)]
print(selected)

selected = a[(a>3) & (a<8)]
print(selected)

[ True False False False False  True  True]
[10  8  7]
[10  2  2  8  7]
[4 5 7]


In [59]:
"""
Exercise
"""
porridge = np.array([79, 65, 50, 63, 56, 90, 85, 98, 79, 51])

cold = porridge[porridge<60]
print(cold)
hot = porridge[porridge>80]
print(hot)
just_right = porridge[(porridge>=60) & (porridge<=80)]
print(just_right)

[50 56 51]
[90 85 98]
[79 65 63 79]
